dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sombreroenpuntas-github"
    token:
        secure: "Fj98oy9pHO8xofABNkwcaVy8moCgVEvjin4RoztlXPmF0PZHqLxfbY0tQUDJqxYdPUvr9CXZC7q3y54UD0daHuJimWfeOo3tIixd4wiyGUt1dABmiXOwEFI7/MFwxQKUHgmr+x+aT+yAacV1q+vLOZkhEjK+hnbiWLD2RfTHwnk+jjLx4ndDt95a+2cU4g2AZ4BF5sKZJ1CgKkVzzHMnKgJ0el2uSEUN7Xil859FtzWtVjaWT01GY1h8ksm0fGrdKBCUYZ3dqOkDzDLocM9Wr1o1f20NB5/XjelpPV4QPBTiFxrMmaxJ/J7LwCWoTFi6KF+GTs1ZcADOGRAQrgZ5VYRWTcFjj1BU1Jazpgit287zfm/Ld22+5DwuI7qrG71XJerNtmE/AwXV39oyl1XipSlhbPas8fv2dfF4sqDaDXWqao3OZZ5zGhrly3/LEWFYF+emd5hZU5KF9FstlOPadpk/WE4EUtZ67VGjSAlHdJVvW6WVFHueR7QxJur4ApGlfXzAOd4iAenR23NR3atXP+NfL6js+TE7N5ww81TiNk4vDzema9AdJvK7LN8Gt0cO7VNzApZvGqNS45c/TqSN/3vh3/HK/4Ow6Nvhix6G6Q0TzivGcHKAEhk531RqMkUSt/pbEmZBElE3yYg1LwzSzABK5XbMl7130Otz5WjFIu8="
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
